version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - contextcheck
    - errorlint
    - exhaustive
    - gocritic
    - godox
    - misspell
    - noctx
    - revive
    - sqlclosecheck
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
